"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import { Loader2, RefreshCw, Search, X, Save, Trash2, ChevronLeft, ChevronRight } from "lucide-react";

export type AdminColumn<T> = { key: keyof T | string; label: string; render?: (row:T)=>ReactNode };

export function AdminPage({title,description,actions,children}:{title:string;description?:string;actions?:ReactNode;children:ReactNode}){
 return <main className="min-w-0 flex-1 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-1 text-[10px] uppercase tracking-[.2em] text-cyan-400">Admin Console</div><h1 className="text-2xl font-semibold tracking-tight text-white sm:text-3xl">{title}</h1>{description&&<p className="mt-2 max-w-3xl text-sm leading-6 text-white/45">{description}</p>}</div>{actions}</div>{children}</div></main>
}
export function StatCard({label,value,sub}:{label:string;value:ReactNode;sub?:string}){return <div className="border border-white/10 bg-white/[.025] p-4"><div className="text-[10px] uppercase tracking-[.16em] text-white/30">{label}</div><div className="mt-2 text-2xl font-semibold text-white">{value}</div>{sub&&<div className="mt-1 text-xs text-white/35">{sub}</div>}</div>}
export function ErrorState({message,onRetry}:{message:string;onRetry?:()=>void}){return <div className="border border-red-400/20 bg-red-400/[.04] p-5 text-sm text-red-200"><p>{message}</p>{onRetry&&<button onClick={onRetry} className="mt-3 inline-flex items-center gap-2 border border-red-300/20 px-3 py-2 text-xs hover:bg-red-300/10"><RefreshCw className="h-3.5 w-3.5"/>Retry</button>}</div>}
export function LoadingState(){return <div className="flex min-h-48 items-center justify-center border border-white/10 bg-white/[.02] text-sm text-white/40"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Loading…</div>}
export function EmptyState({message}:{message:string}){return <div className="border border-dashed border-white/10 p-10 text-center text-sm text-white/35">{message}</div>}
export function SearchBox({value,onChange,placeholder="Search…"}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="flex h-10 min-w-0 items-center gap-2 border border-white/10 bg-white/[.02] px-3"><Search className="h-4 w-4 shrink-0 text-white/30"/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-white/25"/></label>}
export function Button({children,onClick,type="button",disabled,variant="default"}:{children:ReactNode;onClick?:()=>void;type?:"button"|"submit";disabled?:boolean;variant?:"default"|"danger"|"ghost"}){const c=variant==="danger"?"border-red-400/20 text-red-200 hover:bg-red-400/10":variant==="ghost"?"border-white/10 text-white/45 hover:bg-white/5":"border-cyan-400/25 bg-cyan-400/10 text-cyan-100 hover:bg-cyan-400/15";return <button type={type} onClick={onClick} disabled={disabled} className={`inline-flex items-center justify-center gap-2 border px-3 py-2 text-xs transition disabled:cursor-not-allowed disabled:opacity-40 ${c}`}>{children}</button>}
export function DataTable<T extends Record<string,any>>({rows,columns,keyField="id",onSelect,loading}:{rows:T[];columns:AdminColumn<T>[];keyField?:keyof T;onSelect?:(row:T)=>void;loading?:boolean}){if(loading)return <LoadingState/>;if(!rows.length)return <EmptyState message="No database records match the current filters."/>;return <div className="overflow-x-auto border border-white/10"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-white/10 bg-white/[.025]"><tr>{columns.map(c=><th key={String(c.key)} className="px-4 py-3 text-[10px] font-medium uppercase tracking-[.14em] text-white/30">{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r[keyField])||i} onClick={()=>onSelect?.(r)} className={onSelect?"cursor-pointer border-b border-white/5 hover:bg-white/[.025]":"border-b border-white/5"}>{columns.map(c=><td key={String(c.key)} className="max-w-[360px] px-4 py-3 text-sm text-white/65">{c.render?c.render(r):String(r[c.key]??"—")}</td>)}</tr>)}</tbody></table></div>}
export function Pagination({page,totalPages,onPage}:{page:number;totalPages:number;onPage:(p:number)=>void}){if(totalPages<=1)return null;return <div className="mt-4 flex items-center justify-between text-xs text-white/40"><span>Page {page} of {totalPages}</span><div className="flex gap-2"><Button disabled={page<=1} onClick={()=>onPage(page-1)}><ChevronLeft className="h-3.5 w-3.5"/>Previous</Button><Button disabled={page>=totalPages} onClick={()=>onPage(page+1)}>Next<ChevronRight className="h-3.5 w-3.5"/></Button></div></div>}
export function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm sm:items-center sm:p-6"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto border border-white/10 bg-[#0b111b] shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/10 bg-[#0b111b] px-5 py-4"><h2 className="text-sm font-semibold text-white">{title}</h2><button onClick={onClose} className="text-white/40 hover:text-white" aria-label="Close"><X className="h-5 w-5"/></button></div><div className="p-5">{children}</div></div></div>}
export function Field({label,children,required}:{label:string;children:ReactNode;required?:boolean}){return <label className="block space-y-2"><span className="text-[10px] uppercase tracking-[.14em] text-white/35">{label}{required&&" *"}</span>{children}</label>}
export const inputClass="h-10 w-full border border-white/10 bg-white/[.025] px-3 text-sm text-white outline-none placeholder:text-white/20 focus:border-cyan-400/30";
export const textareaClass="min-h-28 w-full resize-y border border-white/10 bg-white/[.025] p-3 text-sm text-white outline-none placeholder:text-white/20 focus:border-cyan-400/30";
export function JsonDetails({value}:{value:any}){const [open,setOpen]=useState(false);return <div><button onClick={()=>setOpen(v=>!v)} className="text-xs text-cyan-300/70 hover:text-cyan-200">{open?"Hide details":"View details"}</button>{open&&<pre className="mt-2 max-h-72 overflow-auto border border-white/10 bg-black/20 p-3 text-[11px] leading-5 text-white/45">{JSON.stringify(value,null,2)}</pre>}</div>}
export async function apiRequest<T=any>(url:string,init?:RequestInit):Promise<T>{const res=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||"Request failed.");return body as T;}
