// fixing deployemeny error
"use client";
import { useEffect,useMemo,useState } from "react";
import { Plus,RefreshCw,Trash2 } from "lucide-react";
import { AdminPage,AdminColumn,Button,DataTable,ErrorState,Field,Modal,Pagination,SearchBox,StatCard,apiRequest,inputClass,textareaClass } from "@/components/admin/AdminUI";

type Row=Record<string,any>;
const endpoint="/api/admin/resource/feedback";
const searchColumns=["description", "type", "page", "trying_to_do"];
const fields: Array<{key:string;label:string;defaultValue?:any;multiline?:boolean}> =[{"key": "status", "label": "Status", "defaultValue": "open", "multiline": false}, {"key": "admin_notes", "label": "Admin notes", "defaultValue": "", "multiline": true}];
const canWrite=true;
function display(v:any){if(v===null||v===undefined||v==="")return "—";if(typeof v==="object")return JSON.stringify(v);return String(v)}
export default function Page(){
 const [rows,setRows]=useState<Row[]>([]); const [pagination,setPagination]=useState<any>({page:1,totalPages:1,total:0}); const [page,setPage]=useState(1); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [editing,setEditing]=useState<Row|null>(null); const [saving,setSaving]=useState(false); const [draft,setDraft]=useState<Row>({});
 async function load(){setLoading(true);setError("");try{const q=new URLSearchParams({page:String(page),pageSize:"25",search,searchColumns:searchColumns.join(",")});const data=await apiRequest<any>(`${endpoint}?${q}`);setRows(data.data||[]);setPagination(data.pagination||{page,totalPages:1,total:0})}catch(e){setError(e instanceof Error?e.message:"Unable to load records.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[page,search]);
 const columns=useMemo<AdminColumn<Row>[]>(()=>{const keys=rows.length?Object.keys(rows[0]).filter(k=>!['metadata','options','explanation','content','circuit','probabilities','results'].includes(k)).slice(0,8):[];return keys.map(key=>({key,label:key.replaceAll("_"," "),render:r=><span className="line-clamp-2">{display(r[key])}</span>}))},[rows]);
 function start(row?:Row){const d=row?{...row}:{};for(const f of fields)if(!(f.key in d))d[f.key]=f.defaultValue??"";setDraft(d);setEditing(row||{})}
 async function save(){setSaving(true);setError("");try{if(editing&&editing.id)await apiRequest(endpoint,{method:"PATCH",body:JSON.stringify({id:editing.id,...draft})});else await apiRequest(endpoint,{method:"POST",body:JSON.stringify(draft)});setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save record.")}finally{setSaving(false)}}
 async function remove(row:Row){if(!confirm("Delete this database record? This action cannot be undone."))return;try{await apiRequest(`${endpoint}?id=${encodeURIComponent(row.id)}`,{method:"DELETE"});setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete record.")}}
 return <AdminPage title="Feedback" description="Review and manage user-submitted feedback stored in the production feedback table." actions={canWrite?<Button onClick={()=>start()}><Plus className="h-3.5 w-3.5"/>Create</Button>:null}><div className="mb-4 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><SearchBox value={search} onChange={v=>{setPage(1);setSearch(v)}} placeholder="Search database records…"/><StatCard label="Records" value={pagination.total??0}/><Button onClick={load}><RefreshCw className="h-3.5 w-3.5"/>Refresh</Button></div>{error&&<div className="mb-4"><ErrorState message={error} onRetry={load}/></div>}<DataTable rows={rows} columns={columns} loading={loading} onSelect={canWrite?(r=>start(r)):undefined}/><Pagination page={pagination.page||page} totalPages={pagination.totalPages||1} onPage={setPage}/>{editing&&canWrite&&<Modal title={editing.id?"Edit record":"Create record"} onClose={()=>setEditing(null)}><div className="space-y-4">{fields.map((f:any)=><Field key={f.key} label={f.label}>{f.multiline?<textarea className={textareaClass} value={String(draft[f.key]??"")} onChange={e=>setDraft(d=>({...d,[f.key]:e.target.value}))}/>:<input className={inputClass} value={typeof draft[f.key]==="object"?JSON.stringify(draft[f.key]):String(draft[f.key]??"")} onChange={e=>setDraft(d=>({...d,[f.key]:e.target.value}))}/>}</Field>)}<div className="flex justify-between pt-2"><div>{editing.id&&<Button variant="danger" onClick={()=>remove(editing)}><Trash2 className="h-3.5 w-3.5"/>Delete</Button>}</div><div className="flex gap-2"><Button variant="ghost" onClick={()=>setEditing(null)}>Cancel</Button><Button onClick={save} disabled={saving}>{saving?"Saving…":"Save"}</Button></div></div></div></Modal>}</AdminPage>}
